# Image Transfer Daemon - Default Configuration
# Copy this file and modify for your specific setup

# Local directory to watch for new images
# Supports ~ for home directory
watch_path: /mnt/c/Users/oir-user/data/images/NIGHT/spring

# Remote server configuration
remote_host: freya
remote_user: winter
remote_base_path: ~/data/images/NIGHT/spring

# File patterns to watch (glob patterns)
# Case-insensitive on Windows
file_patterns:
  - "*.fits"
  - "*.FITS"


# Logging configuration
log_level: INFO
log_directory: ~/logs
log_file: image_transfer.log
log_max_bytes: 52428800     # 50 MB
log_backup_count: 5         # keep 5 rotated files: .1 .. .5


# File handling
min_file_age_seconds: 2  # Wait for file to be stable before transfer
exclude_patterns: []  # Patterns to exclude from transfer
# exclude_patterns:
#   - "*_temp.fits"
#   - "test_*.fits"

